
[package]
name = "parser"
version = "0.1.0"
authors = ["thejohncrafter"]
edition = "2018"

[lib]

[dependencies]
clap = "2.33.3"
automata = {path = "../automata"}
parsergen = {path = "../parsergen"}

