
[package]
name = "parsergen"
version = "0.1.0"
authors = ["thejohncrafter <thejohncrafter@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0.24"

[dependencies.syn]
version = "1.0"
features = ["full"]

